version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build:
      context: ./Backend/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATABASE: stories_audio_auth
      PGHOST: postgres
      PGPORT: 5432

  audio-service:
    build:
      context: ./Backend/audio-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATABASE: stories_audio_audio
      PGHOST: postgres
      PGPORT: 5432

  gateway-service:
    build:
      context: ./Backend/gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - audio-service

  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:3000"
    depends_on:
      - gateway-service

volumes:
  postgres_data:
